//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.CourseParts = new HashSet<CoursePart>();
        }
    
        public int courseID { get; set; }
        public string courseName { get; set; }
        public string courseDescription { get; set; }
        public int tutorID { get; set; }
        public int cost { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePart> CourseParts { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
