//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int enrollmentID { get; set; }
        public int studentID { get; set; }
        public int courseID { get; set; }
        public int tutorID { get; set; }
        public System.DateTime enrollmentDate { get; set; }
        public int statusTypeID { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updateAt { get; set; }
    
        public virtual StatusType StatusType { get; set; }
        public virtual Student Student { get; set; }
    }
}
