//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int lectureID { get; set; }
        public int coursePartID { get; set; }
        public string lectureTitle { get; set; }
        public string lectureLink { get; set; }
        public Nullable<int> duration { get; set; }
        public bool isWatched { get; set; }
        public bool isWatching { get; set; }
        public bool isAvailable { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updateAt { get; set; }
        public int index { get; set; }
    
        public virtual CoursePart CoursePart { get; set; }
    }
}
