//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int submissionID { get; set; }
        public int examID { get; set; }
        public int studentID { get; set; }
        public System.DateTime submissionDate { get; set; }
        public int examTimes { get; set; }
        public int grade { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updateAt { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
