//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorAssignment
    {
        public int tutorAssignmentID { get; set; }
        public int tutorID { get; set; }
        public int courseID { get; set; }
        public int numberOfStudent { get; set; }
        public System.DateTime assignmentDate { get; set; }
        public System.DateTime createAt { get; set; }
        public System.DateTime updateAt { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
